CC = gcc
CCFLAGS = -Wall -std=c99 -O3
LDFLAGS =

OBJS = telxcc.o telxcc.res
EXEC = telxcc.exe

all : $(EXEC)

strip : $(EXEC)
	-strip $<

.PHONY : clean
clean :
	-rm -f $(OBJS) $(EXEC)

$(EXEC) : $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS)

%.o : %.c
	$(CC) -c $(CCFLAGS) -o $@ $<

%.res : %.rc
	windres $< -O coff -o $@
