CC = gcc
CCFLAGS = -Wall -std=c99 -O3
LDFLAGS = -lcomctl32

OBJS = telxcc.o telxcc.res
EXEC = telxcc.exe

all : $(EXEC)

strip : $(EXEC)
	-strip $<

.PHONY : clean
clean :
	-del $(OBJS) $(EXEC)

$(EXEC) : $(OBJS)
	$(CC) -o $@ $(OBJS) $(LDFLAGS) 

%.o : %.c
	$(CC) -c $(CCFLAGS) -o $@ $<

%.res : %.rc
	windres -J rc -O coff -o $@ $< 
